In [2]:
!pip install mysql-connector-python

Collecting mysql-connector-python
  Downloading mysql_connector_python-9.7.0-cp313-cp313-win_amd64.whl.metadata (11 kB)
Downloading mysql_connector_python-9.7.0-cp313-cp313-win_amd64.whl (17.7 MB)
   ---------------------------------------- 0.0/17.7 MB ? eta -:--:--
   - -------------------------------------- 0.5/17.7 MB 3.0 MB/s eta 0:00:06
   - -------------------------------------- 0.8/17.7 MB 2.2 MB/s eta 0:00:08
   --- ------------------------------------ 1.6/17.7 MB 2.5 MB/s eta 0:00:07
   ----- ---------------------------------- 2.4/17.7 MB 2.9 MB/s eta 0:00:06
   ------- -------------------------------- 3.4/17.7 MB 3.2 MB/s eta 0:00:05
   ---------- ----------------------------- 4.5/17.7 MB 3.5 MB/s eta 0:00:04
   --------------- ------------------------ 6.8/17.7 MB 4.7 MB/s eta 0:00:03
   ------------------ --------------------- 8.4/17.7 MB 5.0 MB/s eta 0:00:02
   ----------------------- ---------------- 10.2/17.7 MB 5.4 MB/s eta 0:00:02
   -------------------------- ------------- 11.8/17.7 MB 5.7 MB/s eta 0:00:02
   ------------------------------ --------- 13.6/17.7 MB 6.0 MB/s eta 0:00:01
   ----------------------------------- ---- 15.7/17.7 MB 6.3 MB/s eta 0:00:01
   ---------------------------------------  17.6/17.7 MB 6.7 MB/s eta 0:00:01
   ---------------------------------------- 17.7/17.7 MB 6.4 MB/s  0:00:02
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-9.7.0

In [1]:
!pip install mysql

Collecting mysql
  Downloading mysql-0.0.3-py3-none-any.whl.metadata (746 bytes)
Collecting mysqlclient (from mysql)
  Downloading mysqlclient-2.2.8-cp313-cp313-win_amd64.whl.metadata (5.2 kB)
Downloading mysql-0.0.3-py3-none-any.whl (1.2 kB)
Downloading mysqlclient-2.2.8-cp313-cp313-win_amd64.whl (207 kB)
Installing collected packages: mysqlclient, mysql

   ---------------------------------------- 0/2 [mysqlclient]
   ---------------------------------------- 0/2 [mysqlclient]
   ---------------------------------------- 0/2 [mysqlclient]
   -------------------- ------------------- 1/2 [mysql]
   -------------------- ------------------- 1/2 [mysql]
   ---------------------------------------- 2/2 [mysql]

Successfully installed mysql-0.0.3 mysqlclient-2.2.8

In [4]:
!pip install pymysql

Collecting pymysql
  Downloading pymysql-1.1.3-py3-none-any.whl.metadata (4.3 kB)
Downloading pymysql-1.1.3-py3-none-any.whl (45 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.1.3

In [3]:
import mysql.connector

connection = mysql.connector.connect(
    host="localhost",
    user="root",
    password="MySQL@2510",
    database="student_db",
    port=3306
)

if connection.is_connected():
    print("Connected to MySQL successfully!")

Connected to MySQL successfully!

In [4]:
import mysql.connector
from mysql.connector import Error

# Database configuration

host = "localhost"
database = "student_db"
user = "root"
password = "MySQL@2510"
port = 3306

try:

    # Establish connection

    connection = mysql.connector.connect(
        host=host,
        database=database,
        user=user,
        password=password,
        port=port
    )

    if connection.is_connected():
        print("Connected to MySQL database")

except mysql.connector.Error as error:
    print(f"Failed to connect to database: {error}")




# Create a cursor

cursor = connection.cursor()


# Execute a sample query

cursor.execute("SELECT * FROM Students LIMIT 5")


# Fetch and print results

rows = cursor.fetchall()

for row in rows:
    print(row)


# Close database connection

if 'connection' in locals() and connection.is_connected():
    cursor.close()
    connection.close()

    print("MySQL connection closed")

Connected to MySQL database
(1, 'Aarav Patel', 20, 85, 90, 88, 92)
(2, 'Sophia Smith', 21, 75, 78, 82, 85)
(3, 'Liam Johnson', 22, 88, 91, 84, 89)
MySQL connection closed

In [5]:
!pip install mysql-connector-python SQLAlchemy
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Collecting mysql-connector-python
  Using cached mysql_connector_python-9.7.0-cp313-cp313-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: SQLAlchemy in C:\Users\Lenova\AppData\Roaming\Python\Python313\site-packages (2.0.49)
Requirement already satisfied: greenlet>=1 in C:\Users\Lenova\AppData\Roaming\Python\Python313\site-packages (from SQLAlchemy) (3.4.0)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\Lenova\AppData\Roaming\Python\Python313\site-packages (from SQLAlchemy) (4.15.0)
Using cached mysql_connector_python-9.7.0-cp313-cp313-win_amd64.whl (17.7 MB)
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-9.7.0
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in C:\Users\Lenova\AppData\Roaming\Python\Python313\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\Lenova\AppData\Roaming\Python\Python313\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Lenova\AppData\Roaming\Python\Python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\Users\Lenova\AppData\Roaming\Python\Python313\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\Lenova\AppData\Roaming\Python\Python313\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in C:\Users\Lenova\AppData\Roaming\Python\Python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [21]:
import pandas as pd
from sqlalchemy import create_engine
from sqlalchemy.engine import URL

connection_url = URL.create(
    drivername="mysql+mysqlconnector",
    username="root",
    password="MySQL@2510",
    host="localhost",
    port=3306,
    database="student_db"
)

engine = create_engine(connection_url)

query = "SELECT * FROM Students;"

df = pd.read_sql(query, con=engine)

print(df)

   id          name  age  statistics_marks  python_marks  ml_marks  dl_marks
0   1   Aarav Patel   20                85            90        88        92
1   2  Sophia Smith   21                75            78        82        85
2   3  Liam Johnson   22                88            91        84        89

In [22]:
query = "SELECT * FROM Students;"

df = pd.read_sql(query, con=engine)

df

   id          name  age  statistics_marks  python_marks  ml_marks  dl_marks
0   1   Aarav Patel   20                85            90        88        92
1   2  Sophia Smith   21                75            78        82        85
2   3  Liam Johnson   22                88            91        84        89

In [23]:
query = "SELECT * FROM Students WHERE python_marks > 85 ;"

df = pd.read_sql(query, con=engine)

df

   id          name  age  statistics_marks  python_marks  ml_marks  dl_marks
0   1   Aarav Patel   20                85            90        88        92
1   3  Liam Johnson   22                88            91        84        89

In [24]:
query = "SELECT name, statistics_marks FROM Students;"

df = pd.read_sql(query, con=engine)

df

           name  statistics_marks
0   Aarav Patel                85
1  Sophia Smith                75
2  Liam Johnson                88

In [26]:
query = "SELECT COUNT(*) as Total_students  FROM Students;"

df = pd.read_sql(query, con=engine)

df

   Total_students
0               3

In [28]:
engine.dispose()